
import joe from "./pictures/Joe-Muncy.jpg";
import mark from "./pictures/Mark.jpg";
import martin from "./pictures/Martin.jpg";
import scott from "./pictures/scott.jpg";
import john from "./pictures/John.jpg";
import daniel from "./pictures/daniel.jpg";
import scottM from "./pictures/Scott-Tulino.jpg";
import aaron from "./pictures/Aaron-Sanders.jpg";
import jay from "./pictures/Jay.jpg";
import jeffrey from "./pictures/Jeff_340x464.jpg";
import roberta from "./pictures/Robin_340x464.jpg";
import allison from "./pictures/Allison-Tulino.jpg";
import leo from "./pictures/Leo_340x464.jpg";
import mary from "./pictures/MG-IP_MaryFran_340x464.jpg";
import rebeccah from "./pictures/MG-IP_RGan_340x464.jpg";
import floyd from "./pictures/Floyd-Canfield.jpg";
import david from "./pictures/MG-IP_DavidStar_340x464.jpg";
import robert from "./pictures/Robert-Gnuse.jpg";
import rui from "./pictures/rui.jpg";
import hyung from "./pictures/Hyung_340x464.jpg";
import marcus from "./pictures/Marcus_Luepke_340x464.jpg";
import jayK from "./pictures/JayKlinck_339x461.jpg";
import robertP from "./pictures/MG-IP_BobPolit_340x464.jpg";
import jeffreyS from "./pictures/JeffS_340x464.jpg";
import simone from "./pictures/Simone2_340x464.jpg";
import roman from "./pictures/RomanC_340x464.jpg";
import tony from "./pictures/Tony_C_340x464.jpg";
import tetsu from "./pictures/Tetsu-Yoshida.jpg";
import tingting from "./pictures/Tingting_Liu_340x464.jpg";
import terry from "./pictures/Terry_340x464.jpg";
import shay from "./pictures/Shay-Canfield.jpg";
import kentaro from "./pictures/Kentaro-Higuchi.jpg";
import akiyo from "./pictures/Akiyo-Yoshida.jpg";
import susan from "./pictures/Susan_340x464.jpg";
import sherri from "./pictures/Sherri_340x464.jpg";
import christopher from "./pictures/ChrisE_340x464.jpg";
import soon from "./pictures/SooC_340x464.jpg";
import sally from "./pictures/Sally_Mueller_340x464.jpg";
import anonymous from "./pictures/anonymous.jpg";
export const teamMembers = [
      { id: "Ken", name: "Joe M. (Ken) Muncy", firstName: "Joe", middleName: "M. (Ken)", lastName: "Muncy", 
        firstName: "Joe",
        middleName: "M. (Ken)",
        lastName: "Muncy",
        email: "km@mg-ip.com",
        title: "PRINCIPAL SHAREHOLDER",
        phone: "(703)621-7140 x 101",
        photo: joe,
        education: ["Georgia Institute of Technology (B.S., Industrial Engineering, 1982)", "George Mason University School of Law (J.D., 1988)"],
        memberships: ["AIPLA", "INTA", "AIPPI", "FICPI", "ASIPI"],
        bar: ["Commonwealth of Virginia", "U.S. District Court, Eastern District of Virginia", "U.S. Court of Appeals, Federal Circuit", "Registered to practice before the U.S. Patent and Trademark Office"],
        experience: ["Mr. Muncy focuses his practice on patent prosecution and patent infringement issues for both U.S. and foreign clients. This work includes the preparation and prosecution of many patent applications and the preparation of various infringement, non-infringement and validity opinions. Mr. Muncy also has extensive experience drafting and prosecuting design patent applications, preparing and prosecuting reissue and reexamination applications, and handling appeals before the Patent Trial Appeal Board.", "Mr. Muncy’s specific areas of expertise include the mechanical and electromechanical fields, such as semiconductors, light emitting devices, motors, valves, switches, printed electronics, medical devices, optics, aeronautics, accelerometers, batteries, hydraulics, fuel cells, marine vessels, propulsion systems, touch panels, heat sinks, computer peripheral devices, gambling machines, as well as various ornamental designs for design applications including graphical user interfaces (GUIs), LEDs, bottles, computer cases, automotive parts, cell phone cases and hover boards. Presentations about IP topics have been given by Mr. Muncy in the US, as well as in Canada, Sweden, Denmark, Finland, Australia, Japan, China, Taiwan, Turkey and Dubai."], },
      { id: "Martin", name: "Martin R. Geissler", firstName: "Martin", middleName: "R.", lastName: "Geissler", 
        firstName: "Martin",
        middleName: "R.",
        lastName: "Geissler",
        title: "PRINCIPAL SHAREHOLDER",
        phone: "(703)621-7140 x 102",
        email: "mrg@mg-ip.com",
        photo: martin,
        education: ["New Jersey Institute of Technology (B.S., Electrical Engineering Technology)", "Franklin Pierce Law Center (J.D.)"],
        memberships: ["ABA", "AIPLA", "VPP"],
        experience: ["Mr. Geissler practices in the intellectual property field, specializing particularly in electrical, complex electronics, computer hardware/ software, mechanical arts, and trademarks. He has drafted and prosecuted patent and trademark applications for various major corporations, both domestic and international. Mr. Geissler works directly with inventors and corporate counsel to advise them on establishing, developing and maintaining their patent and trademark portfolios, including licensing. He also prepares legal opinions regarding issues of patentability, patent infringement, and patent validity, and has counseled corporations on how to avoid infringement of various patents."],
        bar: ["New York", "Registered to practice before the U.S. Patent and Trademark Office"], },
      { id: "Mark", name: "Mark E. Olds", firstName: "Mark", middleName: "E.", lastName: "Olds", 
        firstName: "Mark",
        middleName: "E.",
        lastName: "Olds",
        title: "PRINCIPAL SHAREHOLDER",
        email: "meo@mg-ip.com",
        phone: "(703)621-7140 x 103",
        photo: mark,
        education: ["Duquesne University (J.D., cum laude)","Georgetown University Law Center (1998-1999, visiting student)",
        "Case Western Reserve University (MSEE)","Gannon University (BSEE)."],
        memberships: ["ABA", "AIPLA", "Virginia State Bar Intellectual Property Law Section"],
        experience: ["Mr. Olds has experience in various aspects of intellectual property law including U.S. and foreign patent prosecution, reexamination, reissue, portfolio management, patent pooling & standards and client counseling. He has experience in the areas of image processing / multimedia (including MPEG and DVD), digital signal processing, telecommunications (including 3G, CDMA and TDMA), wireless networking (802.11 and Bluetooth) microprocessors, programmable logic controllers, industrial automation, robotics, motors, power systems, laser systems, optics, satellite communications, GPS systems, flight systems and avionics, e-commerce and business method patents."],
        bar:["Commonwealth of Virginia", "Registered to practice before the U.S. Patent and Trademark Office"], },
      { id: "Scott", name: "Scott L. Lowe", firstName: "Scott", middleName: "L.", lastName: "Lowe", 
        firstName: "Scott",
        middleName: "L.",
        lastName: "Lowe",
        title: "PRINCIPAL SHAREHOLDER",
        email: "sll@mg-ip.com",
        phone: "(703)621-7140 x 105",
        photo: scott,
        education: ["George Mason University (BSEE)", "George Mason University School of Law (J.D.)"],
        memberships: "",
        bar: ["Commonwealth of Virginia", "Registered to practice before the U.S. Patent and Trademark Office"],
        experience: ["Mr. Lowe focuses his practice on mechanical, electrical, electro-mechanical and design patent prosecution. In addition to his domestic practice, Mr. Lowe manages the global patent prosecution for several of his clients. Mr. Lowe also provides infringement and validity opinions and assists in litigation matters. Mr. Lowe has drafted and prosecuted patent applications for several well-known domestic and international corporations. Mr. Lowe also has experience in the more unusual aspects of intellectual property law, including reexaminations and reissues.","Mr. Lowe was an Examiner at the United States Patent and Trademark Office for seven years and has practiced in the intellectual property field for over twenty years."], },
      { id: "John", name: "John L. Ciccozzi", firstName: "John", middleName: "L.", lastName: "Ciccozzi", 
        firstName: "John",
        middleName: "L.",
        lastName: "Ciccozzi",
        title: "PRINCIPAL SHAREHOLDER",
        email: "jlc@mg-ip.com",
        phone: "(703)621-7140 x 119",
        photo: john,
        education: ["B.S. in Electrical Engineering from Gannon University, Erie, PA (1983)", "M.S. in Systems Management (Research and Development Option), University of Southern California, Los Angeles, CA (1986)", "J.D. from University of Akron School of Law, Akron, OH (1998)"],
        bar: ["The District of Columbia; The US Patent & Trademark Office. Previously registered as in-house for the state of California."],
        experience: ["Mr. Ciccozzi has 15 years as an electrical engineer and over 12 years experience in the patent field, primarily dealing in all facets of the electrical arts. He was also a Captain in the United States Air Force. He is also a former Patent Examiner in the Microprocessor and Input/Output Devices Art Units at the USPTO.", "He is experienced in a wide range of disciplines, including counseling clients on invalidity and non-infringement, patent portfolio strategy including drafting and prosecuting patent applications, patent portfolio mapping and mining, licensing, litigation and reexamination strategy. He is also experienced in analyzing and evaluating IP and has also mediation and negotiation experience. In addition to his engineering and law firm experience, Mr. Ciccozzi has 6 years of in-house counsel experience at both HTC and Qualcomm."],
        memberships: "", },
      { id: "Daniel", name: "Daniel Podhajny", firstName: "Daniel", middleName: "", lastName: "Podhajny", 
        firstName: "Daniel",
        middleName: "",
        lastName: "Podhajny",
        title: "PRINCIPAL SHAREHOLDER",
        email: "dp@mg-ip.com",
        phone: "(703)621-7140",
        photo: daniel,
        education: ["University of Virginia (Computer Engineering)", "George Mason University (J.D.)"],
        bar: ["Commonwealth of Virginia", "Registered to practice before the U.S. Patent and Trademark Office"],
        experience:["Mr. Podhajny drafts and prosecutes domestic patent applications and PCT applications, and has managed prosecution of applications in many different foreign jurisdictions, including Japan, Korea, China, India and the EPO. Mr. Podhajny also frequently prepares invalidity and non-infringement opinions, and is experienced in various post-grant proceedings at the USPTO, such as Ex Partes Reexaminations. Mr. Podhajny has worked with clients’ engineering resources to modify products/services so as to avoid potential infringement by both NPE patents as well as competitor patents. Mr. Podhajny has performed due diligence in association with several mergers and acquisitions. Mr. Podhajny has also performed due diligence with respect to the acquisition of bulk patent portfolios.", "Mr. Podhajny has experience in many different technical fields, including the following:"],
        memberships: "",
        technicalExpertise:["EVs and EV battery module configurations;", "Battery electrode compositions;", "Cybersecurity, including enterprise network vulnerability analysis;", "Various telecommunications session protocols, including VoIP, PTT, BCCMS, MBMS and e-MBMS, SIP, and IMS;", "Various telecommunications RATs or core network types, including 3G/4G/5G/NR.", "Various telecommunications features including location-based enhancements and presence;", "Internal cell phone OS and power management aspects;", "P2P and D2D protocols (e.g., NFC, Bluetooth, LTE-D, WiFi-Direct, etc.) related to features such as device discovery, ad-hoc session handling protocols (e.g., local leader selection, local interface configurations, etc.) and media streaming (e.g., Miracast-R1 or Miracast-R2);", "The Internet of Things (IoT or IoE) related to features such as IoT control schemes, sensor deployments, and device discovery and onboarding protocols;", "Network routing (e.g., TCP/IP, IPv4 and IPv6, header compression protocols such as RoHC, proxy routing schemes for enhanced compression and/or user anonymity, etc.);", " Mobile advertising and e-commerce platforms;", "Location-positioning systems such as SPS or GPS and hybrid terrestrial-SPS schemes;", "Optics for LIDAR systems;", "Database security systems;", "Video encoding/decoding (e.g., MPEG4)."], },          
      { id: "ScottT", name: "Scott M. Tulino", firstName: "Scott", middleName: "M.", lastName: "Tulino", 
        firstName: "Scott",
        middleName: "M.",
        lastName: "Tulino",
        title: "PRINCIPAL SHAREHOLDER",
        email: "smt@mg-ip.com",
        phone: "(703)621-7140 x 104",
        photo: scottM,
        education: ["B.S. in Ceramic Engineering from Rutgers, the State University of New Jersey (1999)", "JD from University of New Hampshire School of Law (formerly Franklin Pierce Law Center) (2002)"],
        memberships: "",
        bar: ["The Commonwealth of Virginia.", "The U.S. Patent and Trademark Office"],
        experience:["Mr. Tulino focuses his practice on patent prosecution issues, in particular in the mechanical, chemical and electromechanical fields. This work includes preparing new patent applications, responding to Office Actions, and handling appeals before the Board of Patent Appeals and Interferences.", "Prior to joining Muncy, Geissler, Olds & Lowe, P.C., Mr. Tulino spent over 8 years at an intellectual property law boutique in the Washington D.C. area where he prepared and prosecuted patent applications in the mechanical, chemical, and electrical arts for both domestic and foreign clients. Additionally, Mr. Tulino counseled clients on a wide variety of intellectual property matters and lectured clients concerning case law and recent developments in patent law. Mr. Tulino’s specific areas of expertise include semiconductors, cellular and digital communications, image displays, printers, data storage systems, medical devices, automotive components, automotive electronics, light emitting devices, computer software and hardware, and business methods."], },
      { id: "Aaron", name: "Aaron J. Sanders", firstName: "Aaron", middleName: "J.", lastName: "Sanders", 
        firstName: "Aaron",
        middleName: "J.",
        lastName: "Sanders",
        title: "PRINCIPAL SHAREHOLDER",
        email: "ajs@mg-ip.com",
        phone: "(703)621-7140 x 126",
        photo: aaron,
        education: ["The Pennsylvania State University (B.S. Computer Science)","George Mason University School of Law (J.D. cum laude"],
        memberships: "",
        bar:["Commonwealth of Pennsylvania", "U.S. Patent and Trademark Office"],
        experience:["Mr. Sanders drafts and prosecutes domestic patent applications and PCT applications, and has managed the prosecution of applications in many different foreign jurisdictions, including Japan, Korea, China, India, and the EPO.  Mr. Sanders has experience in a number of different technical fields, such as autonomous driving vision systems, Internet of Things (IOT) technologies, telecommunications protocols (e.g., LTE, 5G, etc.), telecommunications session protocols (e.g., VoIP, PTT, etc.), wireless positioning protocols (e.g., OTDOA, RTT, etc.), P2P and D2D protocols, mesh networking protocols, mobile advertising and e-commerce platforms, video processing microprocessor technologies, and others.", "Before joining Muncy, Geissler, Olds & Lowe, PLLC, Mr. Sanders was a patent examiner with more than five years experience in the Data Processing: Database and File Management, Data Structures, and Document Processing Art Unit at the United States Patent & Trademark Office."], },
      { id: "Jay", name: "Jay Hines", firstName: "Jay", middleName: "", lastName: "Hines", 
        firstName: "Jay",
        middleName: "",
        lastName: "Hines",
        title: "PRINCIPAL",
        email: "jh@mg-ip.com",
        phone: "(703)621-7140 x 140",
        photo: jay,
        education: ["University of Notre Dame (BA 1975 cum laude)", "The Lewis and Clark Law School (J.D. 1978)"],
        memberships: ["INTA"],
        bar:["The Commonwealth of Virginia"],
        experience:["Jay Hines concentrates his practice in the areas of trademark and copyright law.  Formerly a Senior Trademark Attorney at the U.S. Patent and Trademark Office (USPTO), he focuses on trademark prosecution, enforcement and inter partes proceedings before the Trademark Trial and Appeal Board.", "While at the USPTO, Mr. Hines served in the Office of the Commissioner for Trademarks and carried out a special assignment involving automation issues related to implementation of the Trademark Law Revision Act of 1988.", "Mr. Hines also has an active international trademark practice.  He manages worldwide trademark portfolios and has written and spoken frequently on the Madrid Protocol; he was a private sector delegate to the World Intellectual Property Organization Diplomatic Conference on the Trademark Law Treaty.  He taught Trademarks and Unfair Competition Law at George Mason University School of Law and U.S. Trademark Law for nine years in a Law Masters  program at the Munich Intellectual Property Law Center."], },
      { id: "Jeffrey", name: "Jeffrey H. Kaufman", firstName: "Jeffrey", middleName: "H.", lastName: "Kaufman", 
        firstName: "Jeffrey",
        middleName: "H.",
        lastName: "Kaufman",
        title: "PRINCIPAL",
        email: "jhk@mg-ip.com",
        phone: "(703)621-7140",
        photo: jeffrey,
        education: ["University of Maryland, College Park (B.A.)", "George Mason University School of Law (J.D.)"],
        memberships: ["AIPLA", "INTA"],
        bar:["Commonwealth of Virginia", "State of Maryland", "District of Columbia", "U.S. Supreme Court", "U.S. Court of Appeals, Federal Circuit", "U.S. Court of Appeals, Fourth Circuit"],
        experience:["Mr. Kaufman was the managing trademark partner of Oblon in Virginia, and moved his practice to MG-IP in 2016. He focuses his practice on trademark and copyright issues. Mr. Kaufman has over 30 years experience in providing large and medium sized domestic and international companies with advice regarding trademark, unfair competition and copyright issues. This includes trademark and copyright litigation, as well as strategies and prosecution advice on protecting famous brands and important works.", "Mr. Kaufman began his career as a trademark attorney at the U.S. Patent & Trademark Office, served as the first chair of the AIPLA’s anti-counterfeiting committee, and has been a speaker and author on issues relating to protecting and enforcing valuable brands."], },
      { id: "Roberta", name: "Roberta S. Bren", firstName: "Roberta", middleName: "S.", lastName: "Bren", 
        firstName: "Roberta",
        middleName: "S.",
        lastName: "Bren",
        title: "PRINCIPAL",
        email: "rsb@mg-ip.com",
        phone: "(571) 549.8200",
        photo: roberta,
        education: ["George Washington University (B.A.)", "Vermont Law School"],
        memberships: ["ABA", "INTA"],
        bar:["Virginia", "New York", "U.S. Supreme Court", "U.S. Court of Appeals, Federal Circuit", "U.S. Court of Appeals, Second Circuit", "U.S. District Court, Eastern and Southern Districts of New York and the Eastern District of Virginia"],
        experience:["Trademarks are not only Roberta Bren’s profession–they are also her passion.  For more than 25 years, Ms Bren has provided cost-effective and practical advice to a broad range of clients from startups to multinational clients. Previously a partner of a large IP boutique firm in Virginia, Ms. Bren’s practice continues to focus on trademark, copyright and other IP issues including transactions, trade dress and unfair competition.", "Ms. Bren began in the IP field as an Examiner at the USPTO.  She is active in numerous organizations including INTA and ABA and is a frequent lecturer on topics ranging from wearable technology to TTAB strategy.  Additionally, Ms. Bren is one of of the contributing authors to “A Legal Strategist’s Guide to TRADEMARK TRIAL AND APPEAL BOARD PRACTICE”, now in it’s Fourth Edition."],
        awards:["Martindale-Hubbell ® AV ® Preeminent 5.0 out of 5", "IP Star, Managing IP Magazine (2013-2023)", "World Trademark Review (WTR) 1000:  The World’s Leading Trademark Professionals 2021-2023", "Euromoney’s Trade Mark Expert Guide 2020-2022",
           "Who’s Who Legal Trademarks:  Lawyers (2016-2020)", "Client Choice Award, IP Media Group (2014-2022)", "ALM’s Women Leaders in Law (2015-2020)"], },
      { id: "Allison", name: "Allison M. Tulino", firstName: "Allison", middleName: "M.", lastName: "Tulino", 
        firstName: "Allison",
        middleName: "M.",
        lastName: "Tulino",
        title: "PRINCIPAL",
        email: "amt@mg-ip.com",
        phone: "(703)621-7140 x 117",
        photo: allison,
        education: ["University of Florida, B.S. Industrial Engineering (1999)", "University of New Hampshire School of Law (formerly Franklin Pierce Law Center), J.D. (2002)"],
        memberships: "",
        bar:["Commonwealth of Virginia", "The District of Columbia", "U.S. Patent and Trademark Office"],
        experience:["Ms. Tulino focuses her practice on patent prosecution and related issues involving mechanical and electrical technologies. She has extensive experience in preparing and prosecuting patent applications relating to a wide range of technologies, including image display devices, telecommunication systems, semiconductor fabrication, automotive components and lighting and automotive control/monitoring. ", "Ms. Tulino also counsels clients in all areas of intellectual property law including the preparation of opinions regarding patentability, invalidity and infringement."], },
      { id: "Leo", name: "Leo V. Gureff", firstName: "Leo", middleName: "V.", lastName: "Gureff", 
        title: "PRINCIPAL",
        email: "lvg@mg-ip.com",
        phone: "(703)621-7140 x 146",
        photo: leo,
        education: ["Franklin Pierce Law Center ( J.D.)", "Franklin Pierce Law Center ( M.I.P.)", "Southern Connecticut State University (B.S. Biology, Chemistry)"],
        memberships: ["AIPPI", "AIPLA"],
        bar:["District of Columbia", "New York State", "The U.S. District Court, Southern District of New York", "U.S. Court of Appeals for the Second Circuit", "The U.S. Patent & Trademark Office"],
        experience:["Mr. Gureff is an intellectual property attorney with expertise in patents, trademarks, copyrights, trade secrets, and other intellectual property matters. Mr. Gureff has extensive experience in drafting and prosecuting utility and design patent applications on behalf of foreign and domestic clients in the areas of mechanical and biomedical arts, materials science, semiconductor technology, polymer chemistry, and chemical processing and synthesis, as well as, trademark application prosecution and trademark enforcement.", "Mr. Gureff also represents technology companies in connection with structuring and negotiating a wide array of complex commercial transactions and agreements, including joint venture agreements, joint research and development agreements, alliance partner agreements, vendor customer agreements, VAR/OEM/distributor agreements, master services agreements, offshore IT and development outsourcing agreements, and data access agreements.   He also represents companies in the domain name dispute resolution proceedings (UDRPs) on both complainant and respondent sides.", "In addition, Mr. Gureff is an experienced lecturer and presenter on the U.S. patent practice and intellectual property law in foreign jurisdictions. He is fluent in Russian and has extensive and ongoing experience traveling to Russia, Ukraine and Belarus to meet with and advise his clients. During these travels, he has given presentations to the Ukrainian Intellectual Property Institute, the Ukraine Minister of Justice, and extensively in Akademgorodok, Novosibirsk, Russia."], },
      { id: "Mary", name: "Mary Frances Love", firstName: "Mary", middleName: "Frances", lastName: "Love",
        title: "PRINCIPAL",
        email: "maryfran@mg-ip.com",
        phone: "(703)621-7140 x 158",
        photo: mary,
        education: ["B.A.  in Political Science from State University of New York at Geneseo 1979", "M.S. in Communications from the Newhouse School of Syracuse University 1983", "J.D. from Georgetown University 1992"],
        memberships: "",
        bar: ["District of Columbia"],
        experience:["Mary Fran Love focuses her practice on domestic and international trademark and copyright matters including trademark clearance, counseling, prosecution, and Trademark Trial and Appeal Board proceedings.  She provides strategic global trademark portfolio advice and counseling to some of the most well-known artists, athletes, and sports leagues in the world.  In addition to a large Sports & Entertainment client base, Mary Fran assists a wide range of clients from multinational corporations in the consumer products field, to medical supplies and Michelin star restaurants.", "Mary Fran works closely with local counsel across the globe planning trademark portfolio strategy for clients.  She also assists foreign law firms with the US application and registration process.  Mary Fran’s team includes experienced IP specialists and trademark attorneys, Spanish language speakers, and patent attorneys for assistance with patents. The team is prepared to help clients with all aspects of IP in the US and overseas."],
        concentration: ["Copyright", "Brand development and protection", "Domain names and cyber protection", "Licensing and Transactions", "Litigation", "Trade Dress", "Trademarks", "Trademark Trial and Appeal Board"], },
      { id: "Rebeccah", name: "Rebeccah Gan", firstName: "Rebeccah", middleName: "", lastName: "Gan", 
        title: "PRINCIPAL",
        email: "rgan@mg-ip.com",
        phone: "(703)621-7140 x 170",
        photo: rebeccah,
        education: ["University of Michigan, Ann Arbor, BA Political Science", "Washington College of Law, American University (Washington, DC), J.D."],
        memberships: ["INTA", "ABA-IPL", "APPI-US", "FICPI"],
        bar: ["NY", "Court of Appeals for the Federal Circuit"],
        experience:["Ms. Gan has over 20 years of experience in domestic and foreign trademark counseling, clearance, prosecution, and enforcement, trademark opposition and cancellation proceedings before the USPTO Trademark Trial and Appeal Board; copyright clearance, registration, and enforcement, and drafting licensing and technology agreements.", "A former USPTO Trademark Examining Attorney, Ms. Gan is a frequent speaker and author on intellectual property topics."], },
      { id: "Floyd", name: "Floyd E. Canfield", firstName: "Floyd", middleName: "E.", lastName: "Canfield", 
        title: "PRINCIPAL",
        email: "fec@mg-ip.com",
        phone: "(703)621-7140 x 131",
        photo: floyd,
        education: ["Hampden-Sydney College (B.S. Biology and Ancient Greek)", "Antonin Scalia Law School at George Mason University "],
        memberships: "",
        bar: ["Commonwealth of Virginia", "Registered to practice before the U.S. Patent and Trademark Office"],
        experience:["Mr. Canfield prepares and prosecutes patent applications in a variety of areas. His focus is in the fields relating to biotechnology and the biological sciences, including genetic technologies and therapeutic compositions, and he has experience handling applications for antimicrobials, medical devices, PCR, vaccines, herbal compositions and extracts, pasteurization, and immunology. In addition, Mr. Canfield has a particular interest in 35 U.S.C §101 issues related to biotechnology and in declaration practice.", "Prior to entering the patent field, Mr. Canfield worked for over ten years in the area of forensic toxicology. He has experience in immunoassay, solid phase extraction, and gas chromatography/mass spectroscopy."], },
      { id: "David", name: "H. David Starr", firstName: "H.", middleName: "David", lastName: "Starr", 
        title: "PRINCIPAL",
        email: "hds@mg-ip.com",
        phone: "(703)621-7140 x 155",
        photo: david,
        education: ["University of Maryland, College Park (B.A.)", "George Washington University Law School (J.D.)"],
        memberships: ["INTA"],
        bar:["District of Columbia", "State of Maryland"],
        experience: ["Mr. Starr joined MG-IP in 2017. He previously served as the partner managing the Trademark Department at an intellectual property firm based in Alexandria, Virginia. His practice involves all aspects of trademark law, including trademark clearance and prosecution, policing and enforcement. ", "In addition to assisting clients on the availability and registration of trademarks, Mr. Starr assists clients in securing trademark registrations in the U.S. and throughout the world. ", "Through Mr. Starr’s policing and enforcement practice, Mr. Starr litigates Opposition and Cancellation matters before the U.S. Patent and Trademark Office’s Trademark Trial and Appeal Board and engages in significant pre-litigation activity including preparing and responding to cease-and-desist demand letters. ", "Mr. Starr also regularly counsels clients on related and broader aspects of intellectual property law. This includes trade dress protection, domain name disputes, IP due diligence and IP audits, and licensing agreements."], },
      { id: "Robert", name: "Robert F. Gnuse", firstName: "Robert", middleName: "F.", lastName: "Gnuse", 
        title: "OF COUNSEL",
        email: "rfg@mg-ip.com",
        phone: "(703)621-7140 x 109",
        photo: robert,
        education: ["Washington University in St. Louis (A.B., 1968)", "George Mason University (J.D., 1984)"],
        memberships: "",
        bar:["Commonwealth of Virginia", "Registered to practice before the U.S. Patent and Trademark Office"],
        experience:["Mr. Gnuse has been practicing in the Intellectual property field since 1968. Mr. Gnuse focuses his practice on electrical, electro-mechanical, computer hardware and mechanical patent application drafting and prosecution. Mr. Gnuse is also a recipient or the American Jurisprudence Award and co-authored: “Combining Applications for Filing in the U.S.,” 26 IDEA 25 (1985). Prior to entering the legal field, Mr. Gnuse was a Patent Examiner at the U.S. Patent and Trademark Office, 1968-1974."], },
      { id: "Hyung", name: "Hyung N. Sohn", firstName: "Hyung", middleName: "N.", lastName: "Sohn", 
        title: "OF COUNSEL",
        email: "hns@mg-ip.com",
        phone: "(703)621-7140 x 145",
        photo: hyung,
        education: ["Carnegie Mellon University (B.S., Electrical & Computer Engineering)", "The George Washington University (M.S., Computer Science)", "George Mason University School of Law (J.D., Intellectual Property Track)"],
        memberships: "",
        experience:["Mr. Sohn primarily focuses on all phases of patent prosecution including drafting original applications, responding to Office Actions and representing clients before the Board of Patent Appeals and Interferences. He has worked with both foreign and domestic clients drafting and prosecuting both domestic and international patent applications. He also has experience in drafting opinions (infringement, non-infringement, validity, invalidity).", "Mr. Sohn specializes in technologies involving semiconductors, telecommunications (including wireless and optical communications), computer hardware and software, electronics, and display technologies among others. Mr. Sohn also has considerable experience in the industry. Prior to becoming a lawyer, he worked as a software engineer for over eight years. He, in conjunction with others, developed and implemented projects for the Food and Drug Administration (FDA), Defense Technical Information Center (DTIC) and for the Department of Defense."],
        bar:"", },
      { id: "Marcus", name: "Marcus H. Luepke", firstName: "Marcus", middleName: "H.", lastName: "Luepke", 
        title: "OF COUNSEL",
        email: "mhl@mg-ip.com",
        phone: "(703)621-7140 x 156",
        photo: marcus,
        education: ["University of Hamburg, School of Law (JD 1990; Doctorate (“Ph.D.”), 1995)", "The George Washington University College of Law (LL.M. in IP, 2007)"],
        memberships: ["GRUR", "ECTA", "INTA", "MARQUES"],
        bar: ["New York", "District of Columbia"],
        experience:["Marcus Luepke has more than 20 years of international experience as trademark attorney in protecting trademarks on a global scale, practicing in both the United States and the European Union. His decade of experience as trademark practitioner in Germany, both in private practice and in-house at BMW, gives him insight into trademark prosecution under the Madrid Protocol, the European Community Trademark system, and in many countries world-wide as well into enforcing trademarks, design rights and copyrights. In the United States, Mr. Luepke has practiced in the corporate legal environment, serving The Coca-Cola Company as trademark counsel and in private practice. This broad range of experience allows him a unique perspective when counseling corporate and firm clients on the management and enforcement of their trademark portfolios and allows Mr. Luepke to do so in a very cost-efficient way. In addition to his international trademark work, Mr. Luepke has experience with the negotiation of coexistence and license agreements for a diverse range of products ranging from financial and automotive to clothing and food and beverage."], },
      { id: "JayK", name: "Jay Klinck", firstName: "Jay", middleName: "", lastName: "Klinck", 
        title: "OF COUNSEL",
        email: "kjk@mg-ip.com",
        phone: "(703)621-7140 x 166",
        photo: jayK,
        education: ["North Carolina Central University School of Law (J.D., cum laude)", "University of Clemson, South Carolina (B.S. Electrical Engineering)"],
        memberships: "",
        bar:["North Carolina", "The U.S. Patent & Trademark Office"],
        experience:["Mr. Klinck has over 14 years of experience in intellectual property law practice, including preparation and prosecuting of domestic patent applications before the United States Patent and Trademark Office and International Patent Applications under the Patent Cooperation Treaty (PCT), as well as US and Hague Convention trademarks. He has advised clients on a range of intellectual property topics including domestic and foreign patent protection, trademarks, business contracts, and IP best practices for both individuals and business entities.  He is experienced in preparing and prosecuting patent applications in a wide range of technologies, including 3G/4G/5G telecommunication, wired and wireless networks, analog and digital electronics, computers and computer systems, LED lighting, power systems, biomedical, mechanical, RF electronics, ultrasound imaging, microfluidics, chromatography, automotive, encryption and digital security, software, semiconductors, data mining, and data visualization.", "Mr. Klinck’s practice has included work in the following technology areas:"],
        technicalExpertise:["Avionics / aviation visualization", "CODECs", "Compression", "Computer software", "Computer systems", "Data processing / data mining / big data collection and evaluation", "Digital and analog electronics", "Digital and RF filtering",  "Electrical machines, motors, and generators",  "Electronic payment systems", "Encryption / decryption", "FLASH memory design and fabrication techniques", "Forward error correction", "Golf training devices", "High-speed serial and parallel interfaces", "Light Emitting Diodes (LED)", "Lighting systems", "Liquid/gas chromatography / mass spectroscopy", "Magnetic navigation", "Mechanical devices", "Medical imaging / ultrasound imaging", "Microcontrollers, microcomputers, ASICs, FPGAs", "Mobile devices", "Musical instruments", "Network security", "Network storage / cloud storage", "Power transmission / high voltage electrical grids", "Radar and phased array antenna processing", "RF transmission / anti-jamming / anti-spoofing", "Semiconductor design and testing", "Semiconductors", "Signal compensation / pre-emphasis", "Telecommunication", "Virtual reality / augmented reality / telepresence", "Wafer process", "Wired and wireless networking"], },
      { id: "RobertP",name: "Robert “Bob” Polit", firstName: "Robert", middleName: "“Bob”", lastName: "Polit", 
        title: "OF COUNSEL",
        email: "rbp@mg-ip.com",
        phone: "(703)621-7140 x 169",
        photo: robertP,
        education: ["The John Marshal Law School (J.D.) (magna cum laude) (West Publishing Award)", "The University of Illinois at Chicago (BS Electrical Engineering) (James Scholar) (Honors College) (Tau Beta Pi)"],
        bar: ["Illinois", "The U.S. District Court, Northern District of Illinois", "The Court of Appeals for the Federal Circuit", 
            "The U.S. Patent & Trademark Office"],
        experience:["Mr. Polit has practical knowledge and experience in RF system design, optical image sensors, memory storage devices, digital filters, speech recognition and enhancement systems, semiconductor devices and manufacturing, artificial intelligence/neural networks, software operating systems (including microkernel OS designs), real-time software, embedded systems, high-speed parallel processing architectures, radar guidance systems, and electronic countermeasures. He has litigated patent infringement actions relating to semiconductor devices/manufacturing, printer technology, medical devices, and hand-held calculators.", "In addition to his law practice experience, Mr. Polit has engineering experience with Northrop Defenses Systems where he helped develop electronic countermeasure systems for the F-15 fighter jet.", "Mr. Polit has over 30 years of experience in practicing intellectual property law. He has established and sustained long-term intellectual property goals of multinational corporations, mid-sized corporations, and start-ups through hands-on participation in intellectual property activities, including:"],
        technicalExpertise:["Preparing patent applications in high technology arts;", "Preparing patent opinions;", "Litigating disputes in both direct and ancillary roles on behalf of plaintiffs and defendants;", "Appeals to the Federal Circuit and USPTO;", "Competitive analysis investigations;" , "Technology licensing;",  "Tracking IP portfolios to target licensing and marketing opportunities."],
        memberships: "", },
      { id: "Simone", name: "Simone Chen", firstName: "Simone", middleName: "", lastName: "Chen", 
        title: "ASSOCIATE",
        email: "simone@mg-ip.com",
        phone: "(703)621-7140 x 152",
        photo: simone,
        education: ["The Johns Hopkins University (B.S. Neuroscience)", "Golden Gate University Law School (J.D.)"],
        bar:["State Bar of California", "U.S. Patent and Trademark Office"],
        memberships: "",
        experience:["Ms. Chen’s practice includes the preparation and prosecution of patent applications in the fields of medical devices, biotechnology, life sciences, consumer products, and pharmaceuticals. Prior to joining Muncy, Geissler, Olds & Lowe, P.C., she worked as a patent prosecution attorney in a Silicon Valley patent firm. Her specialties include consumer electronic devices; endoscopic probes, surgical retractors, and optical imaging; cosmetic devices; software and mobile applications; and design patents.", "Ms. Chen also specializes in trademark practice including trademark clearance, prosecution, portfolio management, and client counseling."], },
      { id: "Roman", name: "Roman Campos", firstName: "Roman", middleName: "", lastName: "Campos", 
        title: "ASSOCIATE",
        email: "arc@mg-ip.com",
        phone: "(703)621-7140 x 271",
        photo: roman,
        education: ["George Mason University, Antonin Scalia Law School, LL.M. in US Law", "Universidad Americana, JD"],
        memberships: ["INTA","ASIPI", "ABA", "NYSBA"],
        bar:["New York Bar", "United States Court of Appeals for the Federal Circuit", "United States District Court for the Eastern District of New York", "United States District Court for the Southern District of New York", "Paraguay Bar"],
        experience:["Mr. Campos works as an Attorney at Muncy, Geissler, Olds & Lowe, P.C. Roman focuses his practice on trademark counseling, prosecution, maintenance, protection, and enforcement of trademark matters, for both U.S. and international clients. He works with a wide range of clients globally, including internationally renowned artists, celebrities, and individuals in diverse fields such as sports, entertainment, and fashion. For Roman, Intellectual Property is about protecting the effort, money, and time his clients put into their businesses. Roman aims to help his clients to achieve the desired goals to protect what is theirs, translate their hard work into profitable returns and promote their businesses."], },
    //   { //     id: "Tony",
    //, name: "Ching (Tony) Chang", firstName: "Ching", middleName: "(Tony)", lastName: "Chang", ,
    //     title: "ASSOCIATE",
    //     email: "tcc@mg-ip.com",
    //     phone: "(703)621-7140 x 171",
    //     photo: tony,
    //     education: ["Temple University Beasley School of Law (J.D.)", "National Taiwan University (M.S., Communication Engineering)", "National Taiwan University (B.S., Electrical Engineering)],"],
    //     memberships: "",
    //     bar: ["Commonwealth of Virginia", "U.S. Patent and Trademark Office"],
    //     experience: ["Before law school, Mr. Chang worked as an in-house patent engineer in a Taiwanese electronic company, where he negotiated with patentees regarding patent validity and infringement disputes and managed patent applications. Also, Mr. Chang worked as a research engineer in wireless communications, including RF and analog circuit design, GUI programming, and protocol programming.", "Mr. Chang drafts and prosecutes patent applications for domestic and international clients, including applications that are essential to various industrial standards. His experience is primarily in the areas of:"],
    //     technicalExpertise:["Analog and digital circuits", "Semiconductor manufacturing processes", "Semiconductor manufacturing equipment", "Telecommunications, including LTE, 5G, Error Correction Codes, and Advanced Television Systems Committee (ATSC) Standards", "Video Coding/Decoding Technology, including H.264, High Efficiency Video Coding (HEVC), and Versatile Video Coding (VVC) standards"],
    // },
      { id: "Tetsu", name: "Tetsu Yoshida", firstName: "Tetsu", middleName: "", lastName: "Yoshida", 
        title: "PATENT AGENT",
        email: "tetsu.yoshida@mg-ip.com",
        phone: "(703)621-7140 x 137",
        photo: tetsu,
        education: ["Kanazawa University, Ishikawa, Japan (B.S., Mechanical Engineering 1993)", "Kanazawa University, Ishikawa, Japan (M.S., Mechanical Engineering 1995)"],
        bar:["Japanese Patent Office, as Benrishi (Reg. No. 11494)","USPTO, as Patent Agent (Reg. No. 70278)"],
        memberships: ["Japanese Patent Attorneys Association"],
        experience:["Tetsu Yoshida has over 15 years of experience in the patent field. Mr. Yoshida previously worked in the engineering and intellectual property law departments of MIZUNO corporation in Osaka, Japan. In 1999, Mr. Yoshida became a patent attorney in Japan. In 2002, Mr. Yoshida moved to the US, where he has continued to develop his patent career as a registered US patent agent.", "Mr. Yoshida provides cost-effective services in prosecuting utility and design patent applications and in conducting patent searches. Mr. Yoshida’s knowledge of Japanese patent law and his Japanese communication skills are particularly advantageous to Japanese companies and firms seeking patent protection in the US, as well as to US companies seeking patent protection in Japan.", "Since 2003, Mr. Yoshida has been an adjunct associate professor teaching intellectual property law at Nara Institute of Science and Technology (NAIST), where he leads research into patent law issues and deals with academic-industrial collaboration."], },
      { id: "Tingting", name: "Tingting Liu", firstName: "Tingting", middleName: "", lastName: "Liu", 
        title: "PATENT AGENT",
        email: "tetsu.yoshida@mg-ip.com",
        phone: "(703)621-7140 x 159",
        photo: tingting,
        education: ["University of Wisconsin-Madison (Ph.D. Biophysical Chemistry)", "Peking University, China (M.S. Chemistry)", "Jilin University, China (B.S. Chemistry)"],
        bar:["U.S. Patent and Trademark Office"],
        memberships: "",
        experience:["Ms. Liu’s practice includes the preparation and prosecution of patent applications in the fields of chemistry, pharmaceuticals, biotechnology and life sciences. Her specialties include organic chemistry, inorganic chemistry, physical chemistry, biochemistry, biomolecular chemistry, polymer chemistry, pharmaceutical chemistry, nanotechnology, LEDs, OLEDs, molecular biology, enzymology, immunology, genetics, cell biology, drug delivery and medical device.", "Prior to joining Muncy, Geissler, Olds & Lowe, P.C., she was a scientist at National Institute of Health (NIH) and a Biophysical Chemistry Postdoctoral Fellow at University of California-Berkeley."], },
      { id: "Terry", name: "Yu-Te (Terry) Chen", firstName: "Yu-Te", middleName: "(Terry)", lastName: "Chen", 
        title: "PATENT AGENT",
        email: "ytc@mg-ip.com",
        phone: "(703)621-7140 x 153",
        photo: terry,
        education: ["University of Washington School of Law (LL.M. in Intellectual Property, 2016)", "National Taiwan University (M.S., 2005)","National Taiwan University (B.S., 2003)"],
        bar:["The U.S. Patent and Trademark Office","The Taiwan Intellectual Property Office"],
        memberships: "",
        experience:["Mr. Chen is a Patent Agent in Muncy, Geissler, Olds & Lowe, P.C., emphasizing on patent preparation and prosecution, and has experience in a variety of technical arts, including biotechnology, biochemistry, biomedical engineering, mechanical engineering and electrical engineering. Prior to joining MG-IP, Mr. Chen worked as a patent attorney in Taiwan, and practiced in domestic and international patent matters. His work experience included global patent procurement and patent validity analysis for numerous Chinese and Taiwanese corporations in different industries."], },
      { id: "Shay", name: "A. Shay Canfield", firstName: "A.", middleName: "Shay", lastName: "Canfield", 
        title: "TECHNICAL ADVISOR",
        email: "asc@mg-ip.com",
        phone: "(703)621-7140 x 113",
        photo: shay,
        education: ["Sweet Briar College (B.A., 1998, Magna Cum Laude)", "Northern Virginia Community College (A.S., in progress)"],
        memberships: "",
        bar:"",
        experience:["Shay Canfield is a Technical Advisor and Group Director at Muncy, Geissler, Olds & Lowe, P.C. She specializes in design and plant patent applications and assists in prosecution of patent applications in the biotechnology fields. Ms. Canfield has drafted Orchidaceae, Asphodelaceae/Hemerocallis, and Cannabaceae plant patent applications. She has also published zoological discussions of the Belgian horse in America and Europe, including evolutionary trends, history of the breed, specific adaptations of the modern horse, and changes in phenotype via centuries of selective breeding.", "She prepares unusual and/or complicated patent prosecution documents before the U.S. Patent and Trademark Office, such as Petitions to Accept Color Drawings, Petitions to Revive, Requests under Rule 48 Correcting Inventorship, Petitions to Restore Priority, reissue applications, Petitions to Make Special, Patent Prosecution Highway (PPH), Quick Path Information Disclosure Statements (QPIDS), and third party submissions.", "Ms. Canfield’s specialized skills include processing complex data streams, independent research, public speaking, training, and analytical comparisons of design objects. With over 20 years of experience training others and lecturing in both patent prosecution and administrative matters, she has prepared and/or given lectures on many topics including:"],
        technicalExpertise:["International PCT practice","US national stage practice","After-final practice","Cost saving strategies for patent prosecution","Unusual inventorship situations  (Virginia CLE approved)","Navigating the legal requirements of 37 CFR 1.84 for patent drawings (Virginia CLE approved)","Establishing and correcting priority claims (Virginia CLE approved)","Formality requirements for new applications"], },
      { id: "Kentaro", name: "Kentaro Higuchi", firstName: "Kentaro", middleName: "", lastName: "Higuchi", 
        title: "TECHNICAL ADVISOR",
        email: "kentaro.higuchi@mg-ip.com",
        phone: "(703)621-7140 x 138",
        photo: kentaro,
        education: ["Radford University, BBA Information Systems (1995)"],
        memberships: "",
        bar: "",
        experience:["Mr. Higuchi has over 15 years of experience in the intellectual property business at a large patent firm and a patent boutique firm. His responsibilities include assisting with translation, interpretation and patent prosecution related matters. His technical areas of expertise include software, mechanical, electrical and electronic equipment, automotive components, printing equipment and optical equipment. He also has experience in assisting with large litigations involving major Japanese corporations in the areas of hybrid engines, photolithographic machines, projectors and electrical hardware tools, as well as with various opinions relating to game devices and software. In addition, he has experience in hardware development and design of mobile computers in Japan."], },
      { id: "Akiyo", name: "Akiyo Yoshida", firstName: "Akiyo", middleName: "", lastName: "Yoshida", 
        title: "TECHNICAL ADVISOR",
        email: "akiyo.yoshida@mg-ip.com",
        phone: "(703)621-7140 x 229",
        photo: akiyo,
        education: ["Kwansei Gakuin University, Kobe, Japan (B.A., 2004, Policy Studies)","International Language Center, Osaka, Japan (Advanced Level Patent Translation Training Program, 2009)"],
        memberships: "",
        bar: "",
        experience:["Ms. Yoshida has over 4 years experience in the patent field. Prior to joining Muncy, Geissler, Olds & Lowe, P.C., Ms. Yoshida worked for a law firm translating Japanese patent specifications and assisting in the prosecution of patent applications for Japanese companies."], },
      { id: "Susan", name: "Susan Brady Blasco", firstName: "Susan", middleName: "Brady", lastName: "Blasco", 
        title: "INTELLECTUAL PROPERTY ADVISOR",
        email: "sbb@mg-ip.comm",
        phone: "(703)621-7140",
        photo: susan,
        education: ["A.A. History, English with honors, Chaffey College, 1974",
            "Certificate – Litigation Paralegal with Honors, UCLA Attorney Assistant Training Program, 1977B.A English, University of California at Los Angeles, 1976"],
        experience:["Fulwider, Patton, Rieber, Lee & Utecht, Intellectual Property Administrator, 1977-1988",
            "Baker & McKenzie-Los Angeles, Intellectual Property Administrator, 1988-1992",
            "Small Larkin, Intellectual Property Administrator, 1992-2002",
            "Birch, Stewart, Kolasch & Birch, LLP, Intellectual Property Administrator, 2002-2014"],
        memberships: "", 
        TrademarkLawAndPracticeExpertise:["Andean Community",
            "Worldwide Cancellation & Opposition Proceedings",
            "Community Trade Mark – Office of Harmonization of the Internal Market",
            "Enforcement",
            "Madrid Agreement & Protocol",
            "OAPI & ARIPO filing systems",
            "Portfolio Management",
            "Prosecution",
            "Searching & Clearance"],
            RegionalExpertise:["East Asia & Pacific",
                    "Europe: European Union",
                    "Latin America & Caribbean",
                    "Middle East & North Africa",
                    "North America (U.S. and Canada)"], 
            "Committees/Subcommittees":["Leadership Development Committee"],
            Languages:["English", "Spanish"]
                },
      { id: "Sherri", name: "Sherri Weisbeck Raslich", firstName: "Sherri", middleName: "Weisbeck", lastName: "Raslich", 
        title: "INTELLECTUAL PROPERTY ADVISOR",
        email: "swr@mg-ip.com",
        phone: "(703)621-7140",
        photo: sherri,
        education: ["Michigan State University College of Law", "University of Wyoming"],
        experience: ["Harness, Dickey and Pierce, P.L.C., Legal Assistant", "Aspire Intellectual Property Law Group, Paralegal"],
        IntellectualPropertyLawAndPracticeExpertise:[
            "Assisting attorneys with management of global trademark portfolios",
            "Trademark Trial and Appeal Board filings and docketing",
            "Supporting clients with policing and enforcement matters",
            "Supporting attorneys in all aspects of USPTO prosecution of trademark applications",
            "Supporting attorneys in all aspects of USPTO maintenance fees and forms of trademark registrations",
            "Client support including domestic clients and foreign associates",
            "Assisting attorneys with management of global patent portfolios",
            "Supporting attorneys in all aspects of USPTO prosecution of utility and design patent applications",
            "Supporting attorneys in all aspects of PCT with US receiving office prosecution of patent applications",
            "Supporting attorneys in all aspects of USPTO maintenance fees of letters patent"],
        memberships: "", },
        {
            id: "Howard",
            name: "Howard Seo",
            firstName: "Howard", middleName: "", lastName: "Seo",
            photo: anonymous,
            email: "hhs@mg-ip.com",
            phone: "(703)621-7140 x 162",
            title: ""
          },
          {
            id: "Linda",
            name: "Linda Gunderson",
            firstName: "Linda", middleName: "", lastName: "Gunderson",
            photo: anonymous,
            email: "lgg@mg-ip.com",
            phone: "(703)621-7140 x 173",
            title: ""
          },
            {
            id: "Lee",
            name: "Lee Hsu",
            firstName: "Lee", middleName: "", lastName: "Hsu",
            photo: anonymous,
            email: "lh@mg-ip.com",
            phone: "(703)621-7140 x 135",
            title: ""
          },
          {
            id: "Carol",
            name: "Carol Guy",
            firstName: "Carol", middleName: "", lastName: "Guy",
            photo: anonymous,
            email: "cag@mg-ip.com",
            phone: "(703)621-7140 x 217",
            title: "Accounting Manager"
          },
          {
            id: "Adesh",
            name: "Adesh Bhargava",
            firstName: "Adesh", middleName: "", lastName: "Bhargava",
            photo: anonymous,
            email: "",
            phone: "(703)621-7140",
            title: ""
          },
      { id: "Christopher", name: "Christopher Emond", firstName: "Christopher", middleName: "", lastName: "Emond", 
        title: "INTELLECTUAL PROPERTY ADVISOR",
        email: "cemond@mg-ip.com",
        phone: "(703)621-7140",
        photo: christopher,
        experience: ["Chris Emond is a senior trademark professional with over 16 years experience in trademark clearance, prosecution, enforcement, and with ex parte and inter partes proceedings before the Trademark Trial and Appeal Board and related appeals to the Federal Circuit. Chris also has substantial experience in filing with the U.S. Copyright Office, including special petitions for review. Prior to joining MGIP, Chris was a senior trademark paralegal at multiple IP boutiques in the DC area.A Marine veteran, Chris enjoys volunteering and spending time with his family, including his daughter, a ROTC student at the University of Wisconsin. Go Badgers!"]}
      ,
      { id: "Sally", name: "Sally Mueller", firstName: "Sally", middleName: "", lastName: "Mueller", 
        title: "HR - OFFICE MANAGER",
        email: "sm@mg-ip.com",
        phone: "(703)621-7140",
        photo: sally,
        education: "",
        memberships: "", },
    // ...more members
  ];